name: C/C++ CI

on: [pull_request]

jobs:
  build-full:
    name: Full build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: alisw/alibuild-action@v1.1
      with:
        package: DebugGUI
        extra_packages: "cmake"
  build-headless:
    name: Headless (no GLFW) build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: alisw/alibuild-action@v1.1
      with:
        package: DebugGUI
        extra_packages: "cmake"
        remove_packages: "glfw-devel"
