name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: alisw/alibuild-action@master
      with:
        package: DebugGUI
        extra_packages: "cmake"
