name: C/C++ CI

on: [pull_request]

jobs:
  build-full:
    name: Full build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: DebugGUI
    - uses: alisw/alibuild-action@v1.4.3
      with:
        package: DebugGUI
        extra_packages: "cmake python3-pip libyaml-cpp-dev"
  build-headless:
    name: Headless (no GLFW) build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: DebugGUI
    - uses: alisw/alibuild-action@v1.4.3
      with:
        package: DebugGUI
        extra_packages: "cmake python3-pip libyaml-cpp-dev"
        remove_packages: "glfw-devel"
